@startuml

autoactivate on

actor UI
boundary AnalyticsController
participant AnalyticsService
participant AnalyticsDAO
database Database

UI -> AnalyticsController : getNewsEngagement
AnalyticsController -> AnalyticsService : getNewsEngagement
par
    AnalyticsService -> AnalyticsDAO : getNewsEngagementCurrentOccupationHeatMapChart
    AnalyticsDAO -> Database
    return
    return
else
    AnalyticsService -> AnalyticsDAO : getNewsEngagementGoalOccupationHeatMapChart
    AnalyticsDAO -> Database
    return
    return
else
    AnalyticsService -> AnalyticsDAO : getNewsEngagementMapChart
    AnalyticsDAO -> Database
    return
    return
end
return
return

@enduml