@startuml

autoactivate on

actor UI
boundary AnalyticsController
participant AnalyticsService
participant AnalyticsDAO
database Database

UI -> AnalyticsController : getCertificationEngagement
AnalyticsController -> AnalyticsService : getCertificationEngagement
par
    AnalyticsService -> AnalyticsDAO : getCertificationEngagementCurrentOccupationHeatMapChart
    AnalyticsDAO -> Database
    return
    return
else
    AnalyticsService -> AnalyticsDAO : getCertificationEngagementGoalOccupationHeatMapChart
    AnalyticsDAO -> Database
    return
    return
else
    AnalyticsService -> AnalyticsDAO : getCertificationEngagementMapChart
    AnalyticsDAO -> Database
    return
    return
end
return
return

@enduml