@startuml

autoactivate on

actor UI
boundary CertificationController
participant CertificationService
participant CertificationDAO
database Database

UI -> CertificationController : getNews
CertificationController -> CertificationService : getNews
CertificationService -> CertificationDAO : getCertificationsBySocCode
CertificationDAO -> Database
return
return
return
return

@enduml