@startuml

autoactivate on

actor Contentful
boundary ContentfulController
participant ContentfulService
participant LearningMaterialService
participant LearningMaterialDAO
database Database

Contentful -> ContentfulController : notifyEntryPublished
ContentfulController -> ContentfulService : putEntry
ContentfulService -> LearningMaterialService : updateLearningMaterial
LearningMaterialService -> LearningMaterialDAO : save
LearningMaterialDAO -> Database
return
return
return
return
return

@enduml