@startuml

autoactivate on

actor UI
boundary OccupationController
participant OccupationService
participant OccupationTrie

UI -> OccupationController : getOccupationsBySocCode
OccupationController -> OccupationService : getOccupationsBySocCode
OccupationService -> OccupationTrie : getBySocCode
return
return
return

@enduml