@startuml

autoactivate on

actor UI
boundary UserController
participant UserService
participant ProfileDAO
database Database

UI -> UserController : updateUserProfile
UserController -> UserService : updateUserProfile
UserService -> ProfileDAO : save
ProfileDAO -> Database
return
return
return
return

@enduml