@startuml

autoactivate on

actor UI
boundary UserController
participant UserService
participant ProfileDAO
database Database

UI -> UserController : getCurrentUserProfile
UserController -> UserService : getUserProfile
UserService -> ProfileDAO : getProfileById
ProfileDAO -> Database
return
return
return
return

@enduml