@startuml

autoactivate on

actor UI
boundary ViewDemandController
participant ViewDemandService
participant ViewDemandDAO
database Database

UI -> ViewDemandController : setDemand
ViewDemandController -> ViewDemandService : setDemand
ViewDemandService -> ViewDemandDAO : setDemand
ViewDemandDAO -> Database
return
return
return
return

@enduml