@startuml

autoactivate on

actor UI
boundary ViewDemandController
participant ViewDemandService
participant ViewDemandDAO
database Database

UI -> ViewDemandController : getDemand
ViewDemandController -> ViewDemandService : getDemand
ViewDemandService -> ViewDemandDAO : getDemand
ViewDemandDAO -> Database
return
return
return
return

@enduml